FROM node:15-alpine AS pnpm
ENV NPM_CONFIG_LOGLEVEL error
ARG PACKAGE_NAME

# Get pnpm
RUN wget -qO - https://get.pnpm.io/v6.js | node - add --global pnpm

# Setup
WORKDIR /opt/pronoundb.org
COPY tsconfig.json .
COPY config.example.json .
COPY pnpm-lock.yaml .
COPY pnpm-workspace.yaml .
COPY packages/ packages/

# Install
RUN pnpm install -r --reporter=append-only --filter @pronoundb/${PACKAGE_NAME}
